version: "3"

services:
  controld:
    build:
      context: .
    environment:
      - SERIAL_PORT=${SERIAL_PORT}
    volumes:
      - ${SERIAL_PORT}:${SERIAL_PORT}
    entrypoint: python /x4controld.py
    privileged: true
